// tests/ui/test_vis_wave_group.cpp — golden tests for the wave-group drivers:
// classic_led, wave, scope, stereo, mirror (cliamp vis_classic_led.go /
// vis_wave.go / vis_scope.go / vis_stereo.go / vis_mirror.go).
//
// Each driver is driven with FIXED inputs (fixed bands, fixed sample windows,
// fixed frame counter, fixed clock) and the resulting CellGrid is dumped with
// ui::dump_grid() — deterministic, no FTXUI in the loop. The dump is compared
// with tests/golden/vis/<mode>.txt ONLY if that golden file is present; when
// it is missing the case is skipped with a WARN comment (the maintainer
// generates the golden files — e.g. from the Go side — later). The structural
// cases port the Go *_test.go assertions (vis_stereo_test.go,
// vis_mirror_test.go) that do not need the Visualizer framework.
#include "ui/vis_drivers/registry.hpp"

#include "ui/cell.hpp"
#include "ui/styles.hpp"
#include "ui/tick.hpp"

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <memory>
#include <span>
#include <string>
#include <string_view>
#include <vector>

using namespace bootamp::ui;
using bootamp::ui::vis_drivers::make_classic_led_driver;
using bootamp::ui::vis_drivers::make_mirror_driver;
using bootamp::ui::vis_drivers::make_scope_driver;
using bootamp::ui::vis_drivers::make_stereo_driver;
using bootamp::ui::vis_drivers::make_wave_driver;

namespace {

using Clock = std::chrono::steady_clock;

// Fixed render target shared by every golden case: 74x5 cells — the Go default
// PanelWidth, so the classic_led bar count (from ui::panel_width()) matches
// the render width and the eased body state is exercised.
constexpr int kRows  = 5;
constexpr int kCols  = 74;
constexpr std::uint64_t kFrame = 42;  // fixed animation counter

// Fixed 10-band spectrum for the band-driven drivers.
const std::vector<float>& fixed_bands() {
  static const std::vector<float> kBands = {
      0.92f, 0.81f, 0.67f, 0.55f, 0.41f, 0.33f, 0.24f, 0.16f, 0.09f, 0.03f};
  return kBands;
}

// Fixed mono waveform (deterministic, no RNG).
std::vector<float> fixed_wave_samples(std::size_t count) {
  std::vector<float> samples(count);
  for (std::size_t i = 0; i < count; ++i) {
    samples[i] = static_cast<float>(0.7 * std::sin(static_cast<double>(i) * 0.25) +
                                    0.3 * std::sin(static_cast<double>(i) * 0.11));
  }
  return samples;
}

// Fixed stereo window: left channel louder than right.
std::vector<std::array<float, 2>> fixed_stereo_samples(std::size_t count) {
  std::vector<std::array<float, 2>> samples(count);
  for (std::size_t i = 0; i < count; ++i) {
    const double p = static_cast<double>(i) * 0.2;
    samples[i]     = {static_cast<float>(0.75 * std::sin(p)),
                      static_cast<float>(0.25 * std::sin(p))};
  }
  return samples;
}

// copy_into adapts a fixed vector into the tap callbacks' span-out signature.
template <typename T>
std::size_t copy_into(std::span<T> dst, const std::vector<T>& src) {
  const std::size_t n = std::min(dst.size(), src.size());
  std::copy_n(src.begin(), n, dst.begin());
  return n;
}

// --- Golden file handling ---------------------------------------------------

// golden_path resolves tests/golden/vis/<mode>.txt. The test may run from the
// repo root, the build dir, or a ctest work dir, so candidate paths are tried
// (relative to the source file, the cwd, and cwd's ancestors). Returns the
// best guess even when nothing exists so the skip comment names a path.
std::filesystem::path golden_path(std::string_view mode) {
  const std::string name = std::string(mode) + ".txt";
  const std::filesystem::path rel = std::filesystem::path("tests") / "golden" / "vis" / name;
  std::vector<std::filesystem::path> candidates;
  const auto src_dir = std::filesystem::path(__FILE__).parent_path();
  candidates.push_back(src_dir / ".." / "golden" / "vis" / name);
  candidates.push_back(std::filesystem::current_path() / rel);
  for (auto dir = std::filesystem::current_path(); dir.has_parent_path();
       dir = dir.parent_path()) {
    candidates.push_back(dir / rel);
  }
  for (const auto& p : candidates) {
    if (std::filesystem::exists(p)) {
      return p;
    }
  }
  return candidates.front();
}

// check_golden: dump-grid comparison against the golden file for `mode`.
// Missing golden files skip the comparison with a WARN comment (the golden is
// generated by the maintainer; the structural tests still run).
void check_golden(std::string_view mode, const std::string& dump) {
  const auto path = golden_path(mode);
  if (!std::filesystem::exists(path)) {
    WARN("golden file " << path << " not present — skipping " << mode
                        << " golden comparison (generate tests/golden/vis/"
                        << mode << ".txt to enable)");
    return;
  }
  std::ifstream in(path);
  std::string expected((std::istreambuf_iterator<char>(in)),
                       std::istreambuf_iterator<char>());
  if (!expected.empty() && expected.back() == '\n') {
    expected.pop_back();
  }
  INFO("golden file: " << path);
  REQUIRE(dump == expected);
}

// --- Structural helpers (ports of the Go test helpers) ----------------------

// brailleBit mirrors the drivers' table (cliamp brailleBit).
constexpr std::array<std::array<std::uint32_t, 2>, 4> kBrailleBit = {{
    {{0x01, 0x08}},
    {{0x02, 0x10}},
    {{0x04, 0x20}},
    {{0x40, 0x80}},
}};

// dot_at reports whether the braille dot (x, y) of the dot grid is set in the
// rendered cell grid (cliamp mirrorDotAt).
bool dot_at(const CellGrid& grid, int x, int y) {
  const int row = y / 4;
  const int col = x / 2;
  return (grid.at(row, col).rune & kBrailleBit[static_cast<std::size_t>(y % 4)]
                                              [static_cast<std::size_t>(x % 2)]) != 0;
}

// dot_count counts set braille dots across the whole grid (cliamp
// mirrorDotCount).
std::size_t dot_count(const CellGrid& grid) {
  std::size_t count = 0;
  for (int r = 0; r < grid.rows(); ++r) {
    for (int c = 0; c < grid.cols(); ++c) {
      const char32_t glyph = grid.at(r, c).rune;
      if (glyph < U'⠀' || glyph > U'⣿') {
        continue;
      }
      for (const auto& row : kBrailleBit) {
        for (const std::uint32_t bit : row) {
          if ((glyph & bit) != 0) {
            ++count;
          }
        }
      }
    }
  }
  return count;
}

// count_runes counts cells whose rune equals `r`.
std::size_t count_runes(const CellGrid& grid, char32_t r) {
  std::size_t count = 0;
  for (int row = 0; row < grid.rows(); ++row) {
    for (int col = 0; col < grid.cols(); ++col) {
      if (grid.at(row, col).rune == r) {
        ++count;
      }
    }
  }
  return count;
}

// count_runes_in_rows counts `r` in the given row range (half-open).
std::size_t count_runes_in_rows(const CellGrid& grid, int row_lo, int row_hi,
                                char32_t r) {
  std::size_t count = 0;
  for (int row = row_lo; row < row_hi; ++row) {
    for (int col = 0; col < grid.cols(); ++col) {
      if (grid.at(row, col).rune == r) {
        ++count;
      }
    }
  }
  return count;
}

// tick_ctx builds a playing context with a fixed clock.
VisTickContext tick_ctx(Clock::time_point now) {
  VisTickContext ctx;
  ctx.now     = now;
  ctx.playing = true;
  return ctx;
}

}  // namespace

// ---------------------------------------------------------------------------
// classic_led
// ---------------------------------------------------------------------------

TEST_CASE("classic_led driver declares the Go analysis spec and cadence") {
  // Pin the frame padding so ui::panel_width() is the Go default 74.
  set_padding(3, 1);
  auto driver = make_classic_led_driver();
  REQUIRE(driver != nullptr);
  // Go AnalysisSpec: classicLEDBarCount(PanelWidth=74) = (74+1)/3 = 25,
  // classicLEDFFTSize = 2048.
  const auto spec = driver->analysis_spec();
  REQUIRE(spec.band_count == 25);
  REQUIRE(spec.fft_size == 2048);

  VisTickContext ctx;
  ctx.playing = true;
  // Go TickInterval: playing || animating -> time.Second/30 (33ms).
  REQUIRE(driver->tick_interval(ctx) == std::chrono::milliseconds(33));
  ctx.playing = false;
  // Not playing and no body content: slow.
  REQUIRE(driver->tick_interval(ctx) == kTickSlow);
  ctx.overlay_active = true;
  REQUIRE(driver->tick_interval(ctx) == kTickSlow);
}

TEST_CASE("classic_led golden render: body LEDs + peak caps on a fixed frame") {
  set_padding(3, 1);
  auto driver = make_classic_led_driver();

  // One tick initializes the eased body/peak state from the fixed bands.
  const auto bands = fixed_bands();
  std::uint64_t frame = 0;
  driver->tick(tick_ctx(Clock::time_point(std::chrono::milliseconds(1000))),
               frame, bands);

  CellGrid grid(kRows, kCols);
  driver->render(bands, kFrame, grid);

  // Deterministic for a fixed frame (also with a second identical render).
  REQUIRE(dump_grid(grid) == dump_grid(grid));
  CellGrid again(kRows, kCols);
  driver->render(bands, kFrame, again);
  REQUIRE(dump_grid(again) == dump_grid(grid));

  // Whole rows carry the row-bottom spectrum tier (Go specWrap): top row
  // high, bottom row low, gap cells colored like the row.
  REQUIRE(grid.at(0, 0).color == kColorSpecHigh);
  REQUIRE(grid.at(kRows - 1, 0).color == kColorSpecLow);
  REQUIRE(grid.at(0, 1).color == grid.at(0, 0).color);
  // Every cell holds one of the LED glyphs (space, ▄, ▀).
  for (int r = 0; r < grid.rows(); ++r) {
    for (int c = 0; c < grid.cols(); ++c) {
      const char32_t rune = grid.at(r, c).rune;
      REQUIRE((rune == U' ' || rune == U'▄' || rune == U'▀'));
    }
  }

  check_golden("classic_led", dump_grid(grid));
}

// ---------------------------------------------------------------------------
// wave
// ---------------------------------------------------------------------------

TEST_CASE("wave driver declares the raw-sample spec and tick cadence") {
  auto driver = make_wave_driver();
  REQUIRE(driver != nullptr);
  // Go spectrumAnalysisSpec(0): raw samples, default FFT size.
  const auto spec = driver->analysis_spec();
  REQUIRE(spec.band_count == 0);
  REQUIRE(spec.fft_size == 2048);

  VisTickContext ctx;
  ctx.playing = true;
  REQUIRE(driver->tick_interval(ctx) == kTickWave);  // Go TickWave while playing
  ctx.playing = false;
  REQUIRE(driver->tick_interval(ctx) == kTickSlow);
  ctx.playing     = true;
  ctx.overlay_active = true;
  REQUIRE(driver->tick_interval(ctx) == kTickSlow);

  REQUIRE(driver->pause_settled());  // no waveform held yet
}

TEST_CASE("wave golden render: braille oscilloscope from a fixed window") {
  auto driver = make_wave_driver();

  const auto samples = fixed_wave_samples(128);
  VisTickContext ctx = tick_ctx(Clock::time_point(std::chrono::milliseconds(1000)));
  ctx.waveform_samples_into = [&samples](std::span<float> dst) {
    return copy_into(dst, samples);
  };
  std::uint64_t frame = 0;
  driver->tick(ctx, frame, {});
  REQUIRE_FALSE(driver->pause_settled());  // waveform held

  CellGrid grid(kRows, kCols);
  driver->render(std::span<const float>{}, kFrame, grid);

  // Deterministic for a fixed frame.
  REQUIRE(dump_grid(grid) == dump_grid(grid));
  CellGrid again(kRows, kCols);
  driver->render(std::span<const float>{}, kFrame, again);
  REQUIRE(dump_grid(again) == dump_grid(grid));

  // Every cell is a braille glyph in its row-bottom spectrum tier (Go
  // specWrap): top row high, bottom row low.
  for (int r = 0; r < grid.rows(); ++r) {
    for (int c = 0; c < grid.cols(); ++c) {
      const char32_t rune = grid.at(r, c).rune;
      REQUIRE(rune >= U'⠀');
      REQUIRE(rune <= U'⣿');
    }
  }
  REQUIRE(grid.at(0, 0).color == kColorSpecHigh);
  REQUIRE(grid.at(kRows - 1, 0).color == kColorSpecLow);

  // A paused tick clears the waveform so the framework can settle (contract).
  driver->tick(tick_ctx(Clock::time_point(std::chrono::milliseconds(2000))),
               frame, {});
  VisTickContext paused = tick_ctx(Clock::time_point(std::chrono::milliseconds(2000)));
  paused.playing = false;
  paused.paused  = true;
  driver->tick(paused, frame, {});
  REQUIRE(driver->pause_settled());

  check_golden("wave", dump_grid(grid));
}

// ---------------------------------------------------------------------------
// scope
// ---------------------------------------------------------------------------

TEST_CASE("scope driver declares the raw-sample spec and tick cadence") {
  auto driver = make_scope_driver();
  REQUIRE(driver != nullptr);
  const auto spec = driver->analysis_spec();
  REQUIRE(spec.band_count == 0);
  REQUIRE(spec.fft_size == 2048);

  VisTickContext ctx;
  ctx.playing = true;
  REQUIRE(driver->tick_interval(ctx) == kTickWave);
  ctx.playing = false;
  REQUIRE(driver->tick_interval(ctx) == kTickSlow);
  REQUIRE(driver->pause_settled());
}

TEST_CASE("scope golden render: Lissajous figure on a fixed frame") {
  auto driver = make_scope_driver();

  const auto samples = fixed_wave_samples(300);
  VisTickContext ctx = tick_ctx(Clock::time_point(std::chrono::milliseconds(1000)));
  ctx.waveform_samples_into = [&samples](std::span<float> dst) {
    return copy_into(dst, samples);
  };
  std::uint64_t frame = 0;
  driver->tick(ctx, frame, {});

  CellGrid grid(kRows, kCols);
  driver->render(std::span<const float>{}, kFrame, grid);

  // Deterministic for a fixed frame.
  REQUIRE(dump_grid(grid) == dump_grid(grid));
  CellGrid again(kRows, kCols);
  driver->render(std::span<const float>{}, kFrame, again);
  REQUIRE(dump_grid(again) == dump_grid(grid));

  // Braille glyphs everywhere, row-tier colors like Go specWrap.
  for (int r = 0; r < grid.rows(); ++r) {
    for (int c = 0; c < grid.cols(); ++c) {
      const char32_t rune = grid.at(r, c).rune;
      REQUIRE(rune >= U'⠀');
      REQUIRE(rune <= U'⣿');
    }
  }
  REQUIRE(grid.at(0, 0).color == kColorSpecHigh);
  REQUIRE(grid.at(kRows - 1, 0).color == kColorSpecLow);
  // A 300-sample window plots real dots (not an empty figure).
  REQUIRE(dot_count(grid) > 0);

  check_golden("scope", dump_grid(grid));
}

// ---------------------------------------------------------------------------
// stereo
// ---------------------------------------------------------------------------

TEST_CASE("stereo driver declares the raw-sample spec and tick cadence") {
  auto driver = make_stereo_driver();
  REQUIRE(driver != nullptr);
  const auto spec = driver->analysis_spec();
  REQUIRE(spec.band_count == 0);
  REQUIRE(spec.fft_size == 2048);

  VisTickContext ctx;
  ctx.playing = true;
  // Go TickInterval: playing -> TickAnim (16ms, the C++ fast tier).
  REQUIRE(driver->tick_interval(ctx) == kTickFast);
  ctx.playing = false;
  REQUIRE(driver->tick_interval(ctx) == kTickSlow);
  ctx.overlay_active = true;
  ctx.playing        = true;
  REQUIRE(driver->tick_interval(ctx) == kTickSlow);
}

// Port of TestStereoDriverReadsAndRendersStereoSamples (driver-level): the tap
// is read once per kTickAnalyze window and the L/R meters render with labels.
TEST_CASE("stereo driver reads and renders stereo samples") {
  auto driver = make_stereo_driver();

  const auto samples = fixed_stereo_samples(64);
  std::size_t calls  = 0;
  const auto t0 = Clock::time_point(std::chrono::milliseconds(1000));
  VisTickContext ctx = tick_ctx(t0);
  ctx.stereo_samples_into = [&](std::span<std::array<float, 2>> dst) {
    ++calls;
    return copy_into(dst, samples);
  };

  std::uint64_t frame = 0;
  driver->tick(ctx, frame, {});
  REQUIRE(calls == 1);
  // A second tick within the kTickAnalyze window must not re-pull.
  driver->tick(tick_ctx(t0), frame, {});
  REQUIRE(calls == 1);
  // Past the window it re-pulls.
  driver->tick(tick_ctx(t0 + kTickAnalyze + std::chrono::milliseconds(1)), frame, {});
  REQUIRE(calls == 2);

  CellGrid grid(kRows, kCols);
  driver->render(std::span<const float>{}, kFrame, grid);

  // Exactly one L and one R label; a peak marker is drawn; no extra fields.
  REQUIRE(count_runes(grid, U'L') == 1);
  REQUIRE(count_runes(grid, U'R') == 1);
  REQUIRE(count_runes(grid, U'■') >= 1);
  // Left channel is louder than right: more lit cells in the top half.
  const std::size_t left_lit =
      count_runes_in_rows(grid, 0, kRows / 2, U'▮');
  const std::size_t right_lit =
      count_runes_in_rows(grid, kRows / 2 + kRows % 2, kRows, U'▮');
  REQUIRE(left_lit > right_lit);

  check_golden("stereo", dump_grid(grid));
}

// Port of TestStereoPausedDecaysMetersToRest (driver-level): paused ticks
// zero the targets and the meters decay to rest within the Go test's cap.
TEST_CASE("stereo meters decay to rest while paused") {
  auto driver = make_stereo_driver();

  // Charge the meters with loud audio first.
  const std::vector<std::array<float, 2>> loud = {
      {0.9f, 0.9f}, {-0.9f, -0.9f}};
  const auto t0 = Clock::time_point(std::chrono::milliseconds(1000));
  std::uint64_t frame = 0;
  for (int i = 0; i < 5; ++i) {
    VisTickContext ctx = tick_ctx(t0 + (i + 1) * kTickSlow);
    ctx.stereo_samples_into = [&](std::span<std::array<float, 2>> dst) {
      return copy_into(dst, loud);
    };
    driver->tick(ctx, frame, {});
  }
  // Charged meters are still animating: the interval stays fast while paused.
  VisTickContext paused;
  paused.paused = true;
  REQUIRE(driver->tick_interval(paused) == kTickFast);

  // Paused ticks empty both needles and peaks instead of freezing them.
  bool settled = false;
  for (int i = 0; i < 240; ++i) {
    paused.now = t0 + (i + 1) * kTickSlow;
    driver->tick(paused, frame, {});
    if (driver->tick_interval(paused) == kTickSlow) {
      settled = true;
      break;
    }
  }
  REQUIRE(settled);  // the meters must settle to rest (Go test cap: 240)
  // Once settled, further paused ticks stay at rest.
  paused.now = t0 + std::chrono::seconds(10);
  driver->tick(paused, frame, {});
  REQUIRE(driver->tick_interval(paused) == kTickSlow);
}

// ---------------------------------------------------------------------------
// mirror
// ---------------------------------------------------------------------------

TEST_CASE("mirror driver declares the 10-band spec and tick cadence") {
  auto driver = make_mirror_driver();
  REQUIRE(driver != nullptr);
  // Go spectrumAnalysisSpec(DefaultSpectrumBands).
  const auto spec = driver->analysis_spec();
  REQUIRE(spec.band_count == 10);
  REQUIRE(spec.fft_size == 2048);

  VisTickContext ctx;
  ctx.playing = true;
  // Go fast renderOnly driver with TickAnim (16ms, the C++ fast tier).
  REQUIRE(driver->tick_interval(ctx) == kTickFast);
  ctx.playing = false;
  REQUIRE(driver->tick_interval(ctx) == kTickSlow);
  ctx.playing        = true;
  ctx.overlay_active = true;
  REQUIRE(driver->tick_interval(ctx) == kTickSlow);
}

TEST_CASE("mirror golden render: persistent axis + symmetric bars") {
  auto driver = make_mirror_driver();

  const auto bands = fixed_bands();
  CellGrid grid(kRows, kCols);
  driver->render(bands, kFrame, grid);

  // Deterministic for a fixed frame.
  REQUIRE(dump_grid(grid) == dump_grid(grid));
  CellGrid again(kRows, kCols);
  driver->render(bands, kFrame, again);
  REQUIRE(dump_grid(again) == dump_grid(grid));

  // Every cell is a braille glyph with a tier color (Go brailleGrid.render).
  for (int r = 0; r < grid.rows(); ++r) {
    for (int c = 0; c < grid.cols(); ++c) {
      const char32_t rune = grid.at(r, c).rune;
      REQUIRE(rune >= U'⠀');
      REQUIRE(rune <= U'⣿');
    }
  }
  // The top-left corner has no dots: empty braille in the low tier.
  REQUIRE(grid.at(0, 0).rune == U'⠀');
  REQUIRE(grid.at(0, 0).color == kColorSpecLow);

  check_golden("mirror", dump_grid(grid));
}

// Port of TestRenderMirrorHasPersistentAxisAndSymmetricBars at the driver
// level (the Go test renders through the Visualizer at PanelWidth 24).
TEST_CASE("mirror renders a persistent axis and symmetric bars") {
  auto driver = make_mirror_driver();

  constexpr int width = 24;
  CellGrid grid(kRows, width);
  std::vector<float> quiet(10, 0.0f);
  driver->render(quiet, 0, grid);

  const int dot_rows = kRows * 4;
  const int dot_cols = width * 2;
  const int span =
      std::min(dot_cols, std::max(2, dot_cols * 84 / 100) -
                             std::max(2, dot_cols * 84 / 100) % 2);
  const int x0     = (dot_cols - span) / 2;
  const int axis_y = dot_rows / 2;

  // The axis runs across the full span.
  for (int x = x0; x < x0 + span; ++x) {
    INFO("axis missing at x=" << x);
    REQUIRE(dot_at(grid, x, axis_y));
  }
  // Bars are vertically symmetric about the axis.
  for (int x = 0; x < dot_cols; ++x) {
    for (int offset = 1; axis_y - offset >= 0 && axis_y + offset < dot_rows;
         ++offset) {
      REQUIRE(dot_at(grid, x, axis_y - offset) == dot_at(grid, x, axis_y + offset));
    }
  }
  // Loud bands draw more dots than silence.
  const std::size_t quiet_dots = dot_count(grid);
  std::vector<float> loud(10, 1.0f);
  CellGrid loud_grid(kRows, width);
  driver->render(loud, 0, loud_grid);
  const std::size_t loud_dots = dot_count(loud_grid);
  REQUIRE(quiet_dots > static_cast<std::size_t>(span));  // more than the axis
  REQUIRE(loud_dots > quiet_dots);
}
